### ISSUE TITLE
Рефакторинг App

### ISSUE THREAD

**Issue by ilyasidorchik** [rusaksenov/react-practice#4]
1. _Расширение файла._ Лучше использовать для компонентов `js`, а не `jsx`. [Ден Абрамов об этом](https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904).

2. _Переменные стейта_. Обычно называют пару: `[value, setValue]`, `[active, isActive]`. Тебе подойдет со словом `counter`.

**Comment by rusaksenov** [comment]
Did
`App.js`
`import React, { useState } from 'react';
import './App.css';
 
const App = () => {
	const [counter, counterState] = useState(0)

	return (
		<div className="App">
			<h1>result</h1>
			<input type="text" value={ counter } disabled />
			<button onClick={ () => { counterState(counter + 1) }}>
				+1
			</button>
		</div>
	);
}

export default App;`

**Comment by ilyasidorchik** [comment]
Руслан, посмотри внимательнее, как называются переменные стейта в примерах [в документации Реакта](https://ru.reactjs.org/docs/hooks-state.html).

**Comment by rusaksenov** [comment]
Да, всё исправил
